/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminInterface;

import AppSystem.AppSystem;
import Customer.Customer;
import Library.Library;
import Library.User.UserAccount;
import Library.User.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class CustomerManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerManagementPanel
     */
    private AppSystem app;
    private UserAccount ua;
    DefaultTableModel tableModel;
    
    public CustomerManagementPanel() {
        initComponents();
    }

    public CustomerManagementPanel(AppSystem app, UserAccount ua){
        initComponents();
        
        this.app = app;
        this.ua = ua;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldusername1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        fieldname1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, 30));
        add(fieldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, 30));
        add(fieldname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 30));

        addBtn.setText("ADD CUSTOMER");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer id", "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 430, 380));

        jLabel1.setText("name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        jLabel2.setText("username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 117, -1, 30));

        jLabel3.setText("password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

        UserAccountDirectory ua = this.app.getUad();

        if(ua.accountExists(fieldusername1.getText(), fieldPassword1.getText(), "customer")) {
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        }
        else {
            // save the customer obj for user and useraccount credentials
            UserAccount user = this.app.getUad().createUserAccount(fieldusername1.getText(), fieldPassword1.getText(), "customer");
            this.app.getCustomerDirectory().createCustomer(user.getAccountid(), fieldname1.getText());
            populate();
        }

    }//GEN-LAST:event_addBtnActionPerformed
    public void populate() {
        
        tableModel.setRowCount(0);
        for(Customer c: this.app.getCustomerDirectory().getCustomerList()) {
            UserAccount u = this.app.getUad().findById(c.getPersonid());
            
            Object[] row = new Object[4];
            
            row[0] = c.getPersonid();
            row[1] = c.getName();
            row[2] = u.getUsername();
            row[3] = u.getPassword();
            
            tableModel.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldname1;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
