/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import AppSystem.AppSystem;
import Branch.Branch;
import Customer.Customer;
import Library.Employee.Employee;
import Library.Employee.Librarian;
import Library.Library;
import Library.User.UserAccount;
import Library.User.UserAccountDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class EmployeeManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibrarianManagementPanel
     */
    private AppSystem app;
    private UserAccount ua;
    private DefaultTableModel empTableModel;
    
//    public LibrarianManagementPanel() {
//        initComponents();
//    }
    
    public EmployeeManagementPanel(AppSystem app, UserAccount ua) {
        initComponents();
        this.setVisible(true);
        
        this.app = app;
        this.ua = ua;
        this.empTableModel = (DefaultTableModel) empTable.getModel();
        
        populateBranch();
        branchCombo.setSelectedItem(null);
        
        populateTable();
    }
    
    public void populateBranch(){
        ArrayList<Branch> allbranches = this.app.getBranchDirectory().getBranches();
        for (Branch b: allbranches){
            branchCombo.addItem(b.getName());
        }
    }
    
    public void populateTable(){
        empTableModel.setRowCount(0);
        
        for (Branch b: this.app.getBranchDirectory().getBranches()){
            if (b.getLibrary().getEmployeeDirectory().getEmployees().size()>0){
                for (Employee e: b.getLibrary().getEmployeeDirectory().getEmployees()){
                
                Object[] row = new Object[5];
            
                row[0] = e;
                row[1] = e.getName();
                row[2] = e.getExperience();
                row[3] = e.getDesignation();
                row[4] = b;
                
                empTableModel.addRow(row);
                }
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldusername1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        fieldname1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        branchCombo = new javax.swing.JComboBox<>();
        fieldexp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 120, 30));
        add(fieldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 120, 30));
        add(fieldname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, 30));

        addBtn.setText("Add Employee");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jLabel5.setText("designation");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));

        jLabel2.setText("password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

        jLabel6.setText("username");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "librarian", "branch manager" }));
        comboRole.setSelectedIndex(-1);
        comboRole.setToolTipText("");
        add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, 30));

        jLabel7.setText("name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 20));

        jLabel8.setText("library branch");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        branchCombo.setSelectedIndex(-1);
        branchCombo.setToolTipText("");
        add(branchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 120, 30));
        add(fieldexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 120, 30));

        jLabel9.setText("experience");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Id", "Name", "Experience", "Designation", "Library"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 400, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory uad = this.app.getUad();
        
        //get user account information
        String userName = fieldusername1.getText();
        String pass = fieldPassword1.getText();
        
        //get employee information
        String name = fieldname1.getText();
        int exp = Integer.valueOf(fieldexp.getText());
        String role = (String) comboRole.getSelectedItem();
        String branch = (String) branchCombo.getSelectedItem();
        
        //check user account unique
        if(uad.accountExists(userName,pass , role)) {
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        }
        //create user account and employee profile
        else {
            UserAccount user = uad.createUserAccount(userName, pass, role);
            
            Library lib = this.app.getBranchDirectory().findBranch(branch).getLibrary();
            
            lib.getEmployeeDirectory().createEmployee(exp, role, name,user.getAccountid(), lib);
            
            populateTable();
        }
    }//GEN-LAST:event_addBtnActionPerformed

        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> branchCombo;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JTable empTable;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldexp;
    private javax.swing.JTextField fieldname1;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
