/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Library.Library;
import Library.User.UserAccount;
import RentalRequest.RentalRequest;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class RentalRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentalRequestPanel
     */    
    private Library library;
    private UserAccount ua;
    DefaultTableModel tableModel;
    
    public RentalRequestPanel() {
        initComponents();
    }
    
    public RentalRequestPanel(Library l, UserAccount ua){
        this.library = l;
        this.ua = ua;
        this.tableModel = (DefaultTableModel) jTable1.getModel();

        populate();
    }
    
    public void populate() {

        tableModel.setRowCount(0);
        for (RentalRequest rr : this.library.getMasterRentalRequestDirectory().getMasterRequestList()) {

            Object[] row = new Object[2];

            row[0] = rr;
            row[1] = rr.getCustomer().getPersonid();

            tableModel.addRow(row);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestID", "Customer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 238));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
