/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.InsurancePlanCatalog;
import javax.swing.JOptionPane;

/**
 *
 * @author emi
 */
public class CreateInsurancePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateInsurancePanel
     */
    private Business business;
    
    public CreateInsurancePanel() {
        initComponents();
    }
    
    public CreateInsurancePanel(Business b){
         initComponents();
         this.business = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCostPerAnnum = new javax.swing.JTextField();
        fieldPlanId = new javax.swing.JTextField();
        fieldPlanName = new javax.swing.JTextField();
        fieldCostPerMonth = new javax.swing.JTextField();
        btnCreateInsurancePlan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Plan Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel3.setText("Plan Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 20));

        jLabel4.setText("Cost Per Annum");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, 30));

        jLabel5.setText("Cost Per Month");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 30));

        fieldCostPerAnnum.setEditable(false);
        add(fieldCostPerAnnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 110, -1));

        fieldPlanId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlanIdActionPerformed(evt);
            }
        });
        add(fieldPlanId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, -1));
        add(fieldPlanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 110, -1));

        fieldCostPerMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCostPerMonthFocusLost(evt);
            }
        });
        add(fieldCostPerMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 110, -1));

        btnCreateInsurancePlan.setText("Create");
        btnCreateInsurancePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInsurancePlanActionPerformed(evt);
            }
        });
        add(btnCreateInsurancePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel1.setText("Create Insurance Plan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateInsurancePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInsurancePlanActionPerformed
        // TODO add your handling code here:
        InsurancePlanCatalog insuranceDirectory = this.business.getInsurancePlanDirectory();
        
        String id = fieldPlanId.getText();
        String name = fieldPlanName.getText();
        String costPerMonth = fieldCostPerMonth.getText();
//        String costPerAnnum = fieldCostPerAnnum.getText();
        
        insuranceDirectory.createInsurancePlan(Integer.valueOf(id),name,Float.valueOf(costPerMonth));
//        this.planCreated.setCostPerAnnum(Float.valueOf(fieldCostPerAnnum.getText()));
        JOptionPane.showMessageDialog(null,"saved");
    }//GEN-LAST:event_btnCreateInsurancePlanActionPerformed

    private void fieldCostPerMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCostPerMonthFocusLost
        // TODO add your handling code here
        
        showCostPerAnnum();
        
    }//GEN-LAST:event_fieldCostPerMonthFocusLost

    private void fieldPlanIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlanIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlanIdActionPerformed
    
    public void showCostPerAnnum(){
        //this calculation does not affect the number saved to back-end, only for showing in create page
        float costPerMonth = Float.valueOf(fieldCostPerMonth.getText());
        float costPerAnnum = costPerMonth*12;
        fieldCostPerAnnum.setText(String.valueOf(costPerAnnum));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateInsurancePlan;
    private javax.swing.JTextField fieldCostPerAnnum;
    private javax.swing.JTextField fieldCostPerMonth;
    private javax.swing.JTextField fieldPlanId;
    private javax.swing.JTextField fieldPlanName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
