/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.InsurancePlan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emi
 */
public class ViewInsurancePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInsurancePanel
     */
    
    private Business business;
    DefaultTableModel insuranceTableModel;
    private InsurancePlan selectedInsurance;
    
    public ViewInsurancePanel() {
        initComponents();
    }
    
    public  ViewInsurancePanel(Business business){
        initComponents();
        
        this.business = business;
        this.insuranceTableModel = (DefaultTableModel) tableInsuranceCatalog.getModel();
        
        displayInsuranceCatlog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewCostPerAnnum = new javax.swing.JTextField();
        viewPlanId = new javax.swing.JTextField();
        viewPlanName = new javax.swing.JTextField();
        viewCostPerMonth = new javax.swing.JTextField();
        btnUpdateInsurancePlan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInsuranceCatalog = new javax.swing.JTable();
        btnViewPlan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setText("Plan Id");

        jLabel3.setText("Plan Name");

        jLabel4.setText("Cost Per Annum");

        jLabel5.setText("Cost Per Month");

        viewCostPerAnnum.setEditable(false);

        viewPlanId.setEditable(false);
        viewPlanId.setText(" ");

        viewCostPerMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                viewCostPerMonthFocusLost(evt);
            }
        });

        btnUpdateInsurancePlan.setText("Update Plan");
        btnUpdateInsurancePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInsurancePlanActionPerformed(evt);
            }
        });

        jLabel1.setText("View And Update Insurance Plans");

        tableInsuranceCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Plan ID", "Plan Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableInsuranceCatalog);

        btnViewPlan.setText("View Plan Details");
        btnViewPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(viewPlanId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnUpdateInsurancePlan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(26, 26, 26)
                            .addComponent(viewCostPerAnnum))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(30, 30, 30)
                            .addComponent(viewCostPerMonth))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(57, 57, 57)
                            .addComponent(viewPlanName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewPlan)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(viewPlanId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewPlanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewCostPerMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewCostPerAnnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btnUpdateInsurancePlan))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnViewPlan)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPlanActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableInsuranceCatalog.getSelectedRow();
        
        if (selectedRow >= 0){
            this.selectedInsurance = (InsurancePlan) tableInsuranceCatalog.getValueAt(selectedRow, 0);
            
            viewPlanId.setText(String.valueOf(selectedInsurance.getPlanId()));
            viewPlanName.setText(selectedInsurance.getPlanName());
            viewCostPerMonth.setText(String.valueOf(selectedInsurance.getCostPerMonth()));
            viewCostPerAnnum.setText(String.valueOf(selectedInsurance.getCostPerAnnum()));
        }else{
            JOptionPane.showMessageDialog(null,"Please select a row!");
        }
    }//GEN-LAST:event_btnViewPlanActionPerformed

    private void btnUpdateInsurancePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInsurancePlanActionPerformed
        // TODO add your handling code here:
        //id does not permit update
        if(!viewPlanId.getText().isEmpty()){
            String name = viewPlanName.getText();      
            String costPerMonth = viewCostPerMonth.getText();
            
            showCostPerAnnum();
            viewCostPerAnnum.getText();
            
            this.selectedInsurance.setPlanName(name);
            this.selectedInsurance.setCostPerMonth(Float.valueOf(costPerMonth));
            this.selectedInsurance.calCostPerAnnum(Float.valueOf(costPerMonth));
            
            JOptionPane.showMessageDialog(null,"Updated");
        }else{
            JOptionPane.showMessageDialog(null,"Please select a row!");
        }
        
        displayInsuranceCatlog();

    }//GEN-LAST:event_btnUpdateInsurancePlanActionPerformed

    private void viewCostPerMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewCostPerMonthFocusLost
        // TODO add your handling code here:
        showCostPerAnnum();
    }//GEN-LAST:event_viewCostPerMonthFocusLost
    
    public void displayInsuranceCatlog(){
        ArrayList<InsurancePlan> insuranceCatalog = this.business.getInsurancePlanDirectory().getInsurancePlans();
        
        if(insuranceCatalog.size()>0){
            insuranceTableModel.setRowCount(0);
            
            for(InsurancePlan ip: insuranceCatalog){
                Object row[] = new Object[2];
                row[0] = ip;//must have an Override toString to avoid showing an object in the table
                row[1] = ip.getPlanName();
                
                this.insuranceTableModel.addRow(row);
            }
        }else{
            System.out.println("Empty catalog");
        }
            
    }
    
    public void showCostPerAnnum(){
        //this calculation does not affect the number saved to back-end, only for showing in create page
        float costPerMonth = Float.valueOf(viewCostPerMonth.getText());
        float costPerAnnum = costPerMonth*12;
        viewCostPerAnnum.setText(String.valueOf(costPerAnnum));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateInsurancePlan;
    private javax.swing.JButton btnViewPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableInsuranceCatalog;
    private javax.swing.JTextField viewCostPerAnnum;
    private javax.swing.JTextField viewCostPerMonth;
    private javax.swing.JTextField viewPlanId;
    private javax.swing.JTextField viewPlanName;
    // End of variables declaration//GEN-END:variables
}
